# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Extras/customization layer for the OTel Collector.
# This fork sends demo telemetry to Datadog US5.

connectors:
  datadog/connector:

extensions:
  datadog/extension:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}

exporters:
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}
    host_metadata:
      enabled: true

processors:
  resource/datadog:
    attributes:
      - key: deployment.environment.name
        value: demo
        action: upsert
      - key: service.namespace
        value: opentelemetry-demo
        action: upsert

service:
  extensions: [datadog/extension]
  pipelines:
    traces:
      processors: [resourcedetection, memory_limiter, resource/datadog, transform/sanitize_spans]
      exporters: [debug, span_metrics, datadog/connector, datadog]
    metrics:
      receivers: [datadog/connector, docker_stats, http_check/frontend-proxy, host_metrics, nginx, otlp, redis, postgresql, prometheus/ad, span_metrics]
      processors: [resourcedetection, memory_limiter, resource/datadog]
      exporters: [debug, datadog]
    logs:
      processors: [resourcedetection, memory_limiter, resource/datadog, transform/sanitize_logs]
      exporters: [debug, datadog]
